CREATE TABLE IF NOT EXISTS `currency_rate` (
    id INT PRIMARY KEY AUTO_INCREMENT,
    rate DECIMAL(10,4) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DELIMITER //

CREATE OR REPLACE TRIGGER update_currency_rate_timestamp
BEFORE UPDATE ON `currency_rate`
FOR EACH ROW
BEGIN
    SET NEW.updated_at = CURRENT_TIMESTAMP;
END //

DELIMITER ;
